### ISSUE TITLE
Eventhub seems to be flaky on prow?

### ISSUE THREAD

**Issue by n3wscott** [knative-sandbox/reconciler-test#124]
```

PASS test/rekt.TestBrokerIngressConformance/Setup/install_trigger#02 (0.11s)
PASS test/rekt.TestBrokerIngressConformance/Setup/broker_is_addressable#02 (0.04s)
PASS test/rekt.TestBrokerIngressConformance/Setup/install_source#02 (3.10s)
PASS test/rekt.TestBrokerIngressConformance/Assert/[Stable/MUST]ingress_supports_v1.0_accept_the_event (4.00s)
=== RUN   TestBrokerIngressConformance/Assert/[Stable/MUST]ingress_supports_v1.0_deliver_the_event
    --- FAIL: TestBrokerIngressConformance/Assert/[Stable/MUST]ingress_supports_v1.0_deliver_the_event (240.00s)
panic: Fail in goroutine after TestBrokerIngressConformance/Setup/install_sink#02 has completed [recovered]
	panic: Fail in goroutine after TestBrokerIngressConformance/Setup/install_sink#02 has completed
goroutine 916 [running]:
testing.tRunner.func1.1(0x24ad140, 0xc0009f60e0)
skipped 20 lines unfold_more
	/root/.gvm/gos/go1.15.5/src/testing/testing.go:1168 +0x5bc
FAIL test/rekt.TestBrokerIngressConformance/Assert/[Stable/MUST]ingress_supports_v1.0_deliver_the_event (240.00s)
=== RUN   TestBrokerIngressConformance
=== PAUSE TestBrokerIngressConformance
=== CONT  TestBrokerIngressConformance
--- FAIL: TestBrokerIngressConformance (309.56s)
    event_info_store.go:163: Assert passed
    event_info_store.go:163: Assert passed
    event_info_store.go:163: Assert passed
    event_info_store.go:163: Assert passed
    event_info_store.go:163: Assert passed
    event_info_store.go:161: Timeout waiting for at least 1 matches.
FAIL test/rekt.TestBrokerIngressConformance (309.56s)
FAIL test/rekt
=== Failed
=== FAIL: test/rekt TestBrokerIngressConformance/Assert/[Stable/MUST]ingress_supports_v1.0_deliver_the_event (240.00s)
    --- FAIL: TestBrokerIngressConformance/Assert/[Stable/MUST]ingress_supports_v1.0_deliver_the_event (240.00s)
panic: Fail in goroutine after TestBrokerIngressConformance/Setup/install_sink#02 has completed [recovered]
	panic: Fail in goroutine after TestBrokerIngressConformance/Setup/install_sink#02 has completed
goroutine 916 [running]:
testing.tRunner.func1.1(0x24ad140, 0xc0009f60e0)
skipped 17 lines unfold_more
testing.tRunner(0xc000627200, 0xc000a67000)
	/root/.gvm/gos/go1.15.5/src/testing/testing.go:1123 +0x203
created by testing.(*T).Run
	/root/.gvm/gos/go1.15.5/src/testing/testing.go:1168 +0x5bc
```

**Comment by n3wscott** [comment]
Ref: https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative_eventing/5049/pull-knative-eventing-reconciler-tests/1369705873512861696

**Comment by n3wscott** [comment]
Found another:

```
=== Failed
=== FAIL: test/rekt TestBrokerIngressConformance/Assert/[Stable/MUST]ingress_supports_v1.0_deliver_the_event#01 (240.00s)
    --- FAIL: TestBrokerIngressConformance/Assert/[Stable/MUST]ingress_supports_v1.0_deliver_the_event#01 (240.00s)
panic: Fail in goroutine after TestBrokerIngressConformance/Setup/install_sink#03 has completed [recovered]
	panic: Fail in goroutine after TestBrokerIngressConformance/Setup/install_sink#03 has completed
```

https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative_eventing/5056/pull-knative-eventing-reconciler-tests/1370078175236722688

https://github.com/knative/eventing/pull/5056

**Comment by slinkydeveloper** [comment]
Will investigate

**Comment by slinkydeveloper** [comment]
```
 panic: Fail in goroutine after TestBrokerIngressConformance/Setup/install_sink#03 has completed [recovered]
	panic: Fail in goroutine after TestBrokerIngressConformance/Setup/install_sink#03 has completed 
```

This panic doesn't make any sense... I think we should find out why this happens first, more than blaming eventshub.

I don't have the logs of the pods (in particular of eventshub pods), so I can't investigate further. Will try to figure out first why we see this panic

**Comment by slinkydeveloper** [comment]
Link to #106

**Comment by slinkydeveloper** [comment]
https://github.com/knative/eventing/issues/5076

**Comment by n3wscott** [comment]
I think the problem is eventshub panics via fatalf in some places where it does not get the correct counts.

**Comment by slinkydeveloper** [comment]
I'm gonna close this as it seems to me the issue is not eventshub, but something is wrong in the context lifecycle, already tracked by other issues. If you find any evidence something is wrong in eventshub, reopen
