### ISSUE TITLE
Eventshub segfault when trying to send a non-conformant version.

### ISSUE THREAD

**Issue by vaikas** [knative-sandbox/reconciler-test#150]
Trying to send an event with a non-conformant version like this:
```
		source := feature.MakeRandomK8sName("source")
		eventshub.Install(source,
			eventshub.StartSenderToResource(broker.Gvr(), brokerName),
			eventshub.InputHeader("ce-specversion", version),
			eventshub.InputHeader("ce-type", "sometype"),
			eventshub.InputHeader("ce-source", "400.request.sender.test.knative.dev"),
			eventshub.InputHeader("ce-id", uuid),
			eventshub.InputBody("{}}"),
		)(ctx, t)
```

Results in this:
```
vaikas@villes-mbp eventing-rabbitmq % kubectl -n test-mlxqsdzo logs source-pmkrjvle
{"level":"info","ts":"2021-03-22T18:23:23.665Z","caller":"logging/config.go:116","msg":"Successfully created the logger."}
{"level":"info","ts":"2021-03-22T18:23:23.668Z","caller":"logging/config.go:117","msg":"Logging level set to: info"}
{"level":"info","ts":"2021-03-22T18:23:23.668Z","caller":"logging/config.go:79","msg":"Fetch GitHub commit ID from kodata failed","error":"open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":"2021-03-22T18:23:23.668Z","logger":"eventshub","caller":"eventshub/main.go:54","msg":"Events Hub environment configuration: {EventGenerators:[sender] EventLogs:[recorder logger]}"}
{"level":"info","ts":"2021-03-22T18:23:23.668Z","logger":"eventshub","caller":"recorder_vent/constructor.go:53","msg":"Recorder vent environment configuration: {AgentName:observer-default PodName:source-pmkrjvle Port:8080}"}
{"level":"info","ts":"2021-03-22T18:23:23.739Z","logger":"eventshub","caller":"recorder_vent/constructor.go:64","msg":"Going to send events to pod 'source-pmkrjvle' in namespace 'test-mlxqsdzo'"}
{"level":"info","ts":"2021-03-22T18:23:23.740Z","logger":"eventshub","caller":"sender/sender.go:93","msg":"Sender environment configuration: {SenderName:source-pmkrjvle Sink:http://broker-ingress.knative-eventing.svc.cluster.local/test-mlxqsdzo/default Delay:5 ProbeSink:true ProbeSinkTimeout:60 InputEvent: EventEncoding:binary InputHeaders:map[ce-id:94e7efb2-12f1-4205-991b-20718a63baf1 ce-source:400.request.sender.test.knative.dev ce-specversion:19.0 ce-type:sometype] InputBody:{}} AddTracing:false AddSequence:false IncrementalId:false Period:5 MaxMessages:1}"}
{"level":"info","ts":"2021-03-22T18:23:23.740Z","logger":"eventshub","caller":"sender/sender.go:104","msg":"will sleep for 5s"}
{"level":"info","ts":"2021-03-22T18:23:28.740Z","logger":"eventshub","caller":"sender/sender.go:106","msg":"awake, continuing"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x164b4be]

goroutine 35 [running]:
knative.dev/reconciler-test/pkg/test_images/eventshub/sender.Start(0x1c5c5a0, 0xc00021a570, 0xc0001ee2e0, 0x0, 0x0)
	knative.dev/reconciler-test@v0.0.0-20210319220953-d0acc6d8ec47/pkg/test_images/eventshub/sender/sender.go:216 +0x63e
main.startEventGenerators.func2(0x0, 0x0)
	knative.dev/reconciler-test@v0.0.0-20210319220953-d0acc6d8ec47/cmd/eventshub/main.go:91 +0x3c
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc00021a000, 0xc0001ee300)
	golang.org/x/sync@v0.0.0-20201207232520-09787c993a3a/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.0.0-20201207232520-09787c993a3a/errgroup/errgroup.go:54 +0x66
```

**Comment by slinkydeveloper** [comment]
Seems like the panic fixed in https://github.com/knative-sandbox/reconciler-test/commit/5af4bb3fa38677fdcb7e6e1240315ebb82bc6ba8, did you refreshed the test image build?

**Comment by vaikas** [comment]
haha, yes, was just going to close the issue, fixed to the latest and seems to work.
