### ISSUE TITLE
Cannot run tests from Goland

### ISSUE THREAD

**Issue by slinkydeveloper** [knative-sandbox/reconciler-test#39]
I cannot run the example tests from the IDE, configuring with the proper build tag and environment variables, I get this:

```
/usr/lib/golang/bin/go tool test2json -t /tmp/___TestRecorder_in_knative_dev_reconciler_test_test_example -test.v -test.run ^\QTestRecorder\E$
2020/11/17 19:46:43 PWD:  /home/slinkydeveloper/go/src/knative.dev/reconciler-test/test/example
2020/11/17 19:46:43 FILENAME:  /home/slinkydeveloper/go/src/knative.dev/reconciler-test/test/example/config/echo/echo.go
2020/11/17 19:46:43 PWD:  /home/slinkydeveloper/go/src/knative.dev/reconciler-test/test/example
2020/11/17 19:46:43 FILENAME:  /home/slinkydeveloper/go/src/knative.dev/reconciler-test/pkg/eventshub/resources.go
{"level":"info","ts":1605638803.8537316,"logger":"fallback","caller":"injection/injection.go:61","msg":"Starting informers..."}
level All, state Any

=== RUN   TestRecorder
=== PAUSE TestRecorder
=== CONT  TestRecorder
ko publish -B knative.dev/reconciler-test/test/example/cmd/echo
error attempting to ko publish: exit status 1
--- FAIL: TestRecorder (0.22s)
panic: exit status 1 [recovered]
	panic: exit status 1

goroutine 16 [running]:
testing.tRunner.func1.1(0x19acce0, 0xc0003ebac0)
	/usr/lib/golang/src/testing/testing.go:999 +0x319
testing.tRunner.func1(0xc0003cca20)
	/usr/lib/golang/src/testing/testing.go:1002 +0x402
panic(0x19acce0, 0xc0003ebac0)
	/usr/lib/golang/src/runtime/panic.go:969 +0x166
knative.dev/reconciler-test/pkg/environment.(*MagicGlobalEnvironment).Environment(0xc0003eb920, 0xc0003eb9a0, 0x3, 0x3, 0x32e419cb, 0x32e419cb0000000f, 0x5fb41a93, 0xc00055bf70)
	/home/slinkydeveloper/go/src/knative.dev/reconciler-test/pkg/environment/magic.go:73 +0x2bf
knative.dev/reconciler-test/test/example.TestRecorder(0xc0003cca20)
	/home/slinkydeveloper/go/src/knative.dev/reconciler-test/test/example/main_test.go:117 +0x93
testing.tRunner(0xc0003cca20, 0x1b1e398)
	/usr/lib/golang/src/testing/testing.go:1050 +0xdc
created by testing.(*T).Run
	/usr/lib/golang/src/testing/testing.go:1095 +0x28b

Process finished with exit code 1
``` 

My configuration:

![Schermata del 2020-11-17 19-51-10](https://user-images.githubusercontent.com/6706544/99433836-535fcb80-290e-11eb-99c1-478351084aa3.png)

Running from the command line with `SYSTEM_NAMESPACE=knative-eventing go test -v -tags=e2e ./test/example` just works fine.

**Comment by slinkydeveloper** [comment]
It seems like this doesn't happen anymore, I'll reopen if it reproduces again
